FROM maven:3.9-eclipse-temurin-21

WORKDIR /home/app

COPY pom.xml .
RUN mvn dependency:go-offline -B

EXPOSE 8080
EXPOSE 5005

ENTRYPOINT ["mvn", "spring-boot:run", \
  "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", \
  "-Dspring-boot.run.profiles=dev", \
  "-Dspring.devtools.restart.enabled=true", \
  "-Dspring.devtools.livereload.enabled=true"]