package br.com.ifsp.classify.exceptions;

public enum ExceptionCode {
    VALIDATION_ERROR("VALIDATION_ERROR"),
    MISSING_FIELD("MISSING_FIELD"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    INVALID_CPF("INVALID_CPF"),
    INVALID_EMAIL("INVALID_EMAIL"),
    INVALID_PHONE("INVALID_PHONE"),
    INVALID_ADDRESS("INVALID_ADDRESS"),
    INVALID_ROLE("INVALID_ROLE"),
    INVALID_CLASSROOM_CAPACITY("INVALID_CLASSROOM_CAPACITY"),
    INVALID_CLASS_TIME("INVALID_CLASS_TIME"),
    CLASSROOM_DISABLED("CLASSROOM_DISABLED"),
    DATA_INTEGRITY("DATA_INTEGRITY"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    DUPLICATE_RECORD("DUPLICATE_RECORD"),
    RESOURCE_IN_USE("RESOURCE_IN_USE"),
    UNAUTHORIZED("UNAUTHORIZED"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    private final String code;

    ExceptionCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
